# Generated by Django 5.2 on 2025-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
